"""
===============================================================================
Universal Blockchain Platform (UBP)

Module
------
models.ethereum.transaction

Purpose
-------
Ethereum-specific transaction domain models.

This module extends the universal UBP transaction model with Ethereum
Virtual Machine (EVM) specific transaction attributes.

This module contains data models only.

It does NOT:
- connect to Ethereum nodes
- use Web3
- sign transactions
- broadcast transactions
- perform transaction analysis


Architecture
------------

Ethereum Network
        |
        ▼
Ethereum Services
        |
        ▼
Ethereum Transaction Model
        |
        ▼
Reports / API / Analytics


Author
------
Jaramogi Diddy


Platform
--------
Universal Blockchain Platform (UBP)


Version
-------
3.0 Enterprise
===============================================================================
"""


from __future__ import annotations


###############################################################################
# Imports
###############################################################################

from dataclasses import dataclass
from decimal import Decimal
from typing import Any
from typing import Dict
from typing import Optional


from models.transaction import (
    Transaction,
    TransactionConfirmation,
    TransactionFee,
    TransactionMetadata,
    TransactionParticipant,
    TransactionStatus,
    TransactionType,
)



###############################################################################
# Ethereum Transaction Log
###############################################################################


@dataclass(
    frozen=True,
    slots=True,
)
class EthereumTransactionLog:
    """
    Represents an Ethereum event log entry.

    Ethereum logs are generated by smart contracts through
    LOG opcodes and are commonly used for:

    - ERC-20 transfers
    - NFT events
    - Contract state changes
    """


    address: str


    topics: tuple[str, ...]


    data: str



###############################################################################
# End Part 1
###############################################################################
###############################################################################
# Ethereum Transaction Receipt
###############################################################################


@dataclass(
    frozen=True,
    slots=True,
)
class EthereumTransactionReceipt:
    """
    Ethereum transaction execution result.

    Represents the information returned by an Ethereum node after
    a transaction has been mined.

    Contains:
    - execution status
    - block information
    - gas consumption
    - contract creation details
    - emitted logs
    """


    block_number: Optional[int]


    block_hash: Optional[str]


    transaction_index: Optional[int]


    status: Optional[int]


    gas_used: Optional[int]


    cumulative_gas_used: Optional[int]


    contract_address: Optional[str]


    logs: tuple[EthereumTransactionLog, ...]



###############################################################################
# Ethereum Gas Information
###############################################################################


@dataclass(
    frozen=True,
    slots=True,
)
class EthereumGasInfo:
    """
    Ethereum gas execution information.

    This model stores EVM transaction fee details.

    Examples
    --------

    Legacy Ethereum transaction:

        gas_price

    EIP-1559 transaction:

        max_fee_per_gas
        max_priority_fee_per_gas
        effective_gas_price
    """


    gas_limit: int


    gas_used: Optional[int]


    gas_price: Optional[int]


    max_fee_per_gas: Optional[int]


    max_priority_fee_per_gas: Optional[int]


    effective_gas_price: Optional[int]



###############################################################################
# End Part 2
##############################################################################################################################################################
# Universal Transaction Model
###############################################################################


@dataclass(
    frozen=True,
    slots=True,
    kw_only=True,
)
class Transaction:
    """
    Universal blockchain transaction representation.

    This is the core transaction model used throughout UBP.

    It represents concepts common across blockchain networks.

    Blockchain-specific implementations should extend this model.

    Examples
    --------
    Ethereum adds:
        - nonce
        - gas
        - chain id
        - calldata

    Bitcoin adds:
        - inputs
        - outputs
        - satoshi fees
    """


    tx_hash: str


    network: str


    sender: TransactionParticipant


    receiver: TransactionParticipant


    asset: str


    amount: Decimal


    status: TransactionStatus


    transaction_type: TransactionType


    timestamp: Optional[int] = None


    fee: Optional[TransactionFee] = None


    confirmation: Optional[
        TransactionConfirmation
    ] = None


    metadata: Optional[
        TransactionMetadata
    ] = None



@dataclass(
    frozen=True,
    slots=True,
    kw_only=True,
)
class EthereumTransaction(Transaction):
    """
    Ethereum-specific transaction model.

    Extends the universal transaction model with EVM execution details
    such as nonce, gas parameters, calldata, and receipt information.
    """


    nonce: int


    chain_id: int


    gas: EthereumGasInfo


    input_data: str


    function_selector: Optional[str] = None


    contract_address: Optional[str] = None


    receipt: Optional[EthereumTransactionReceipt] = None



###############################################################################
# Transaction Builder Helpers
###############################################################################


def create_transaction_metadata(
    data: Optional[Dict[str, Any]] = None,
) -> TransactionMetadata:
    """
    Create transaction metadata safely.

    Parameters
    ----------
    data:
        Optional metadata dictionary.

    Returns
    -------
    TransactionMetadata
    """


    return TransactionMetadata(

        data=data or {}

    )



def create_transaction_fee(
    amount: Decimal,
    asset: str,
) -> TransactionFee:
    """
    Create a transaction fee model.

    Parameters
    ----------
    amount:
        Fee amount.

    asset:
        Fee currency.

    Returns
    -------
    TransactionFee
    """


    return TransactionFee(

        amount=amount,

        asset=asset,

    )
###############################################################################
# Ethereum Transaction Factory Helper
###############################################################################


def create_ethereum_transaction(
    *,
    tx_hash: str,
    network: str,
    sender: TransactionParticipant,
    receiver: TransactionParticipant,
    amount: Decimal,
    status: TransactionStatus,
    transaction_type: TransactionType,
    nonce: int,
    chain_id: int,
    gas: EthereumGasInfo,
    asset: str = "ETH",
    input_data: str = "0x",
    function_selector: Optional[str] = None,
    contract_address: Optional[str] = None,
    fee: Optional[TransactionFee] = None,
    metadata: Optional[TransactionMetadata] = None,
    receipt: Optional[EthereumTransactionReceipt] = None,
) -> EthereumTransaction:
    """
    Create an Ethereum transaction model.
    """


    return EthereumTransaction(

        tx_hash=tx_hash,

        network=network,

        sender=sender,

        receiver=receiver,

        asset=asset,

        amount=amount,

        status=status,

        transaction_type=transaction_type,

        nonce=nonce,

        chain_id=chain_id,

        gas=gas,

        input_data=input_data,

        function_selector=function_selector,

        contract_address=contract_address,

        fee=fee,

        metadata=metadata,

        receipt=receipt,

    )


###############################################################################
# End Part 3
###############################################################################
###############################################################################
# Ethereum Serialization Helpers
###############################################################################


def ethereum_transaction_to_dict(
    transaction: EthereumTransaction,
) -> Dict[str, Any]:
    """
    Convert Ethereum transaction model into
    serializable dictionary format.

    Useful for:

    - API responses
    - JSON output
    - Database storage
    - Transaction reports
    """


    return {

        "tx_hash":
            transaction.tx_hash,


        "network":
            transaction.network,


        "sender":
            transaction.sender.address,


        "receiver":
            transaction.receiver.address,


        "asset":
            transaction.asset,


        "amount":
            str(transaction.amount),


        "status":
            transaction.status.value,


        "transaction_type":
            transaction.transaction_type.value,


        "nonce":
            transaction.nonce,


        "chain_id":
            transaction.chain_id,


        "gas": {

            "limit":
                transaction.gas.gas_limit,

            "used":
                transaction.gas.gas_used,

            "gas_price":
                transaction.gas.gas_price,

            "max_fee_per_gas":
                transaction.gas.max_fee_per_gas,

            "max_priority_fee_per_gas":
                transaction.gas.max_priority_fee_per_gas,

            "effective_gas_price":
                transaction.gas.effective_gas_price,

        },


        "input_data":
            transaction.input_data,


        "function_selector":
            transaction.function_selector,


        "contract_address":
            transaction.contract_address,


        "receipt": (

            {

                "block_number":
                    transaction.receipt.block_number,

                "block_hash":
                    transaction.receipt.block_hash,

                "status":
                    transaction.receipt.status,

                "gas_used":
                    transaction.receipt.gas_used,

                "contract_address":
                    transaction.receipt.contract_address,

                "logs_count":
                    len(
                        transaction.receipt.logs
                    ),

            }

            if transaction.receipt

            else None

        ),

    }



###############################################################################
# Public Exports
###############################################################################


__all__ = [

    "EthereumTransactionLog",

    "EthereumTransactionReceipt",

    "EthereumGasInfo",

    "EthereumTransaction",

    "create_ethereum_transaction",

    "ethereum_transaction_to_dict",

]



###############################################################################
# End Module
###############################################################################